plugins:
  - jekyll-redirect-from

exclude: [README.md,"run-jekyll.sh"]

encoding: UTF-8

future: yes

redcarpet:
  extensions: [ "tables" ]

baseurl: /voms

issue_base_url: https://issues.infn.it/jira/browse/

voms:
    website: http://italiangrid.github.io/voms

authors:
  francesco:
    display_name: Francesco Giacomini
    gravatar:
    email: francesco.giacomini@cnaf.infn.it
    github: giacomini
  enrico:
    display_name: Enrico Vianello
    gravatar: 4f496230f3e42d606024e16c5f389611
    email: enrico.vianello@cnaf.infn.it
    github: enricovianello
